# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-IE-PermanentTSB
version:      0.04
version_from: lib/Finance/Bank/IE/PermanentTSB.pm
installdirs:  site
requires:
    Date::Calc:                    5.4
    HTML::TokeParser:              2.37
    WWW::Mechanize:                1.34

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
